# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-24 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='city_name')),
                ('desc', models.CharField(max_length=200, verbose_name='description')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='org_name')),
                ('desc', models.TextField(verbose_name='org_description')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click_numbers')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite_nums')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='cover_pic')),
                ('address', models.CharField(max_length=150, verbose_name='org_locations')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='AtTheCity')),
            ],
            options={
                'verbose_name': 'course_organization',
                'verbose_name_plural': 'course_organization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='teacher_name')),
                ('work_years', models.IntegerField(default=0, verbose_name='work_years')),
                ('work_company', models.CharField(max_length=50, verbose_name='working_company')),
                ('work_position', models.CharField(max_length=50, verbose_name='working_position')),
                ('points', models.CharField(max_length=50, verbose_name='teaching_posts')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite_nums')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click_nums')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='AtTheOrganization')),
            ],
            options={
                'verbose_name': 'teachers',
                'verbose_name_plural': 'teachers',
            },
        ),
    ]
