# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': 'Course_Organization', 'verbose_name_plural': 'Course_Organization'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teachers', 'verbose_name_plural': 'Teachers'},
        ),
    ]
