# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-24 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='course_name')),
                ('desc', models.CharField(max_length=300, verbose_name='course_description')),
                ('detail', models.TextField(verbose_name='course_detail')),
                ('degree', models.CharField(choices=[('primary', 'Primary'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=2)),
                ('learn_times', models.IntegerField(default=0, verbose_name='learn_times(Minutes)')),
                ('students', models.IntegerField(default=0, verbose_name='students_count')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite_count')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='cover_pic')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click_numbers')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_times')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='resource_name')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='resource_files')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_times')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course_resource',
                'verbose_name_plural': 'course_resource',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='chapter_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_times')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='video_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_times')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='chapter')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
            },
        ),
    ]
